import Provider from "./Provider";
import "./globals.css";
import type { Metadata } from "next";
import BrowserBlocker from "@/components/BrowserBlocker";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Nihongo Meister",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <Provider>
        <body>
          <main className="w-[375px] h-full mx-auto bg-gradient-to-b from-main via-secondary to-main text-sub">
            {/* <BrowserBlocker /> */}
            <Header />
            <div>{children}</div>
            <Navbar />
          </main>
        </body>
      </Provider>
    </html>
  );
}
