import Provider from "./Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BrowserBlocker from "@/components/BrowserBlocker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nihongo Meister",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <BrowserBlocker />
          <div className="mt-30">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
