import Provider from "./Provider";
import "./globals.css";
import type { Metadata } from "next";
import BrowserBlocker from "@/components/BrowserBlocker";
import Navbar from "@/components/Navbar";
import Topbar from "@/components/Topbar";

export const metadata: Metadata = {
  title: "Nihongo Meister",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <Provider>
        <body className="bg-gray-700">
          {/* <BrowserBlocker /> */}
          <Topbar />
          <div>{children}</div>
          <Navbar />
        </body>
      </Provider>
    </html>
  );
}
